services:
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper_data:/bitnami/zookeeper

  kafka:
    image: bitnami/kafka:3.3.2
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      # Listen on all interfaces:
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092
      # Advertise to clients as kafka:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT 
      # Make sure inter-broker traffic also uses PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    depends_on:
      - zookeeper
    volumes:
      - kafka_data:/bitnami/kafka

  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fraud_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  elasticsearch:
    image: bitnami/elasticsearch:latest
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/bitnami/elasticsearch/data

  kibana:
    image: bitnami/kibana:latest
    environment:
      - KIBANA_ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
  
  transactionservice:
    build:
      context: .                      # repo root
      dockerfile: TransactionService/Dockerfile          # path to the Dockerfile
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:8080
      - Kafka__BootstrapServers=kafka:9092
      - Elasticsearch__Uri=http://elasticsearch:9200
    depends_on:
      - kafka
    ports:
      - "5003:8080"                        # host 5003 → container 80

  frauddetectorservice:
    build: 
      context: .                      # repo root 
      dockerfile: FraudDetectorService/Dockerfile        
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5000
      - ConnectionStrings__FraudDatabase=Host=postgres;Port=5432;Database=fraud_db;Username=postgres;Password=postgres
      - Kafka__BootstrapServers=kafka:9092
      - Elasticsearch__Uri=http://elasticsearch:9200
    depends_on:
      - kafka
      - postgres
    ports:
      - "5001:5000" 

  frontend:
    build: ./fraud-frontend
    depends_on:
      - frauddetectorservice    
    ports:
      - "8080:80"               

volumes:
  zookeeper_data:
  kafka_data:
  postgres_data:
  elasticsearch_data:
